# Generated by Django 3.2.9 on 2021-11-11 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_auto_20211111_0635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['date_created']},
        ),
    ]
